<a href="https://colab.research.google.com/github/lynn-rotich/Python_Basics/blob/main/Simple_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import math

In [9]:
import pandas as pd

# pd.read_excel() - read excel files
# pd.read_json() - read json files

student_date = pd.read_csv('StudentsPerformance.csv')
student_date.head(5)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [10]:
# Base
import csv

with open('StudentsPerformance.csv') as student_data:
  reader = csv.DictReader(student_data)
  students = list(reader)

for index in range(5):
  print(students[index])

{'gender': 'female', 'race/ethnicity': 'group B', 'parental level of education': "bachelor's degree", 'lunch': 'standard', 'test preparation course': 'none', 'math score': '72', 'reading score': '72', 'writing score': '74'}
{'gender': 'female', 'race/ethnicity': 'group C', 'parental level of education': 'some college', 'lunch': 'standard', 'test preparation course': 'completed', 'math score': '69', 'reading score': '90', 'writing score': '88'}
{'gender': 'female', 'race/ethnicity': 'group B', 'parental level of education': "master's degree", 'lunch': 'standard', 'test preparation course': 'none', 'math score': '90', 'reading score': '95', 'writing score': '93'}
{'gender': 'male', 'race/ethnicity': 'group A', 'parental level of education': "associate's degree", 'lunch': 'free/reduced', 'test preparation course': 'none', 'math score': '47', 'reading score': '57', 'writing score': '44'}
{'gender': 'male', 'race/ethnicity': 'group C', 'parental level of education': 'some college', 'lunch': 'standard', 'test preparation course': 'none', 'math score': '76', 'reading score': '78', 'writing score': '75'}

In [15]:
# Accessing a row
students[2]

{'gender': 'female',
 'race/ethnicity': 'group B',
 'parental level of education': "master's degree",
 'lunch': 'standard',
 'test preparation course': 'none',
 'math score': '90',
 'reading score': '95',
 'writing score': '93'}

In [ ]:
# iloc - Integer Location {dataframe.iloc[rowcindex, column index]}
# loc - Label/Location

In [14]:
# Accessing a column
print([row['lunch'] for row in students[:10]])

['standard', 'standard', 'standard', 'free/reduced', 'standard', 'standard', 'standard', 'free/reduced', 'free/reduced', 'free/reduced']

In [20]:
student_date.iloc[2]

gender                                  female
race/ethnicity                         group B
parental level of education    master's degree
lunch                                 standard
test preparation course                   none
math score                                  90
reading score                               95
writing score                               93
Name: 2, dtype: object